### ISSUE TITLE
actividad_5_practica_de_conjuntos_equipo_isaias_paola_ariadna_arisbeth

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-equipo-isaias-paola-ariadna-arisbeth#1]
[matemáticas_discretas_López_Domínguez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-equipo-isaias-paola-ariadna-arisbeth/files/12755078/matematicas_discretas_Lopez_Dominguez.pdf)

**Comment by Felix-Angel** [comment]
Portada: 25%
Procedimiento: 25%
Figuras, ilustraciones y figuras: 25%
Resultados y conclusiones: 25%
Total: 20/20
Evaluó equipo de Diego, Daniel, Félix Y Mayra.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
